((nil . ((cider-offer-to-open-cljs-app-in-browser . nil)
         (cider-default-cljs-repl . shadow)
         (cider-preferred-build-tool . shadow-cljs)
         (cider-shadow-default-options . ":web")))
 (js-mode . ((eval . (apheleia-mode))))
 (css-mode . ((eval . (apheleia-mode)))))
